### ISSUE TITLE
Should we remove the validation part from this project? How would you do it?

### ISSUE THREAD

**Issue by alexsavio** [enter-at/python-aws-lambda-handlers#103]

**Comment by sleistner** [comment]
Node Lambda handlers (https://github.com/enter-at/node-aws-lambda-handlers) take a rather simple approach of leaving the validation part entirely to the hosting project.
It handles `BadRequestError` which might be raised by handler/adapter implementations.

**Comment by alexsavio** [comment]
Do you mean we could indicate through examples for the hosting project developer to raise a `BadRequestError` in their handler/adapter implementation? So the main task here would be to remove all validation implementations and put them as example?

**Comment by sleistner** [comment]
Yes, the simpler the better. As it seems a new validation framework is popping up every other month, I think in the long run we are better off leaving the decision of how to validate to users of this module. Having good documentation with examples will explain and drive our design decision.

**Comment by alexsavio** [comment]
Alright, thanks! On it.
